import { useTranslation } from 'react-i18next';
import { api } from '../lib/api';
import { DownloadIcon } from './icons';

/**
 * Export controls.
 *
 * Excel is generated by the server and fetched as an ordinary download. PDF is the browser's
 * own Print to PDF driven by the print stylesheet, which handles Arabic text shaping
 * correctly and avoids shipping a headless browser or embedded fonts on the server.
 */
export function ExportBar({
  report,
  params,
}: {
  report: 'daily' | 'monthly' | 'annual';
  params: Record<string, string | number | undefined>;
}) {
  const { t } = useTranslation();

  const linkClass =
    'tap inline-flex items-center gap-1.5 rounded-xl border border-line bg-white px-3 text-sm font-semibold text-ink';

  return (
    <div className="no-print flex flex-wrap items-center gap-2">
      <a className={linkClass} href={api.exportUrl(report, 'xlsx', params)}>
        <DownloadIcon />
        {t('reports.exportExcel')}
      </a>
      <button type="button" className={linkClass} onClick={() => window.print()}>
        {t('common.print')}
      </button>
    </div>
  );
}
